"""Preflight shared hooks before deleting a worktree that may own their runtime."""

from __future__ import annotations

import shlex
import subprocess
import sys
from pathlib import Path


def hook_repair(
    repo: Path, removed: Path, main: Path, replacement: Path | None = None
) -> tuple[Path, str, str] | None:
    result = subprocess.run(
        ["git", "rev-parse", "--git-path", "hooks/pre-commit"],
        cwd=repo,
        capture_output=True,
        text=True,
        check=True,
    )
    hook = Path(result.stdout.strip())
    if not hook.is_absolute():
        hook = repo / hook
    if not hook.exists():
        return None
    if hook.absolute().is_relative_to(
        removed.absolute()
    ) or hook.resolve().is_relative_to(removed.resolve()):
        raise ValueError(
            "Effective pre-commit hook itself is inside the removed worktree"
        )
    content = hook.read_text()
    lines = content.splitlines(keepends=True)
    assignments = [
        i for i, line in enumerate(lines) if line.startswith("INSTALL_PYTHON=")
    ]
    runtime_inside = False
    if len(assignments) == 1:
        values = shlex.split(lines[assignments[0]].split("=", 1)[1])
        if len(values) == 1:
            interpreter = Path(values[0])
            if not interpreter.is_absolute():
                interpreter = repo / interpreter
            runtime_inside = interpreter.absolute().is_relative_to(
                removed.absolute()
            ) or interpreter.resolve().is_relative_to(removed.resolve())
    if str(removed) not in content and not runtime_inside:
        return None
    if "File generated by pre-commit" not in content or len(assignments) != 1:
        raise ValueError(
            "Shared hook references removed worktree; repair its dependencies first"
        )
    candidates = (
        [replacement]
        if replacement
        else [main / ".venv/bin/python", Path(sys.executable)]
    )
    for candidate in candidates:
        if (
            candidate is None
            or candidate.absolute().is_relative_to(removed.absolute())
            or candidate.resolve().is_relative_to(removed.resolve())
        ):
            continue
        try:
            checked = subprocess.run(
                [str(candidate), "-c", "import pre_commit"],
                capture_output=True,
                check=False,
            )
        except OSError:
            continue
        if checked.returncode:
            continue
        lines[assignments[0]] = f"INSTALL_PYTHON={shlex.quote(str(candidate))}\n"
        repaired = "".join(lines)
        if str(removed) in repaired:
            raise ValueError("Hook has additional dependencies in the removed worktree")
        return hook, content, repaired
    raise ValueError("No replacement Python can import pre_commit; worktree preserved")
